# Precompilation regression for the component layer (DESIGN-COMPONENTS.md §2–§7).
#
# A `@mixin`/`@node` declared in a *precompiled package* must survive to runtime. The
# spec store and loadable-kind registration once lived in ROSNode's process-global
# `_MIXINS`/`_NODE_KINDS`; a consuming package's top-level declarations mutated those
# during the package's own precompile, and that mutation was discarded with ROSNode's
# deserialized state before the package cache was written — so at runtime `mixin_spec`
# threw and `node_kind` returned nothing. The fix stores each mixin's spec in a `const`
# in the *defining* module (reached by `mixin_spec(::Type{M})` dispatch) and defers
# name registration to the module's load hook `ros_init!`.
#
# This builds a throwaway environment that reuses the active resolved Manifest (so the
# fixture precompiles against THIS ROSNode without re-resolving the workspace's local
# deps), precompiles the fixture, then loads it in a fresh subprocess that asserts every
# declaration resolved. The subprocess's nonzero exit on any failed check is the signal.
using Test

# Assertions run in the fresh subprocess (written to the temp env below, not a tracked
# file): loading PrecompMixinFixture there deserializes its precompile image — its module
# body does NOT re-run — so these prove the `@mixin`/`@param`/`@node`/authored
# declarations survived precompilation. A top-level `@testset` throws on any failure, so
# a failed check exits the process nonzero — the signal the parent reads.
const _PRECOMP_CHECK = raw"""
using PrecompMixinFixture
using ROSNode
using Test

const F = PrecompMixinFixture
const B = PrecompMixinFixture.Byo

@testset "precompiled @mixin declarations survive to runtime" begin
    sp = ROSNode.mixin_spec(F.Counter)
    @test [p.name for p in sp.params] == [:fps, :label]
    @test Set((p.name, p.kind) for p in sp.ports) ==
          Set([(:tick, :timer), (:ingest, :subscription), (:out, :publisher), (:q, :service)])

    ingest = only(p for p in sp.ports if p.name == :ingest)
    @test ingest.msgtype === F.Ping                     # @hears carries the authored type

    @test ROSNode.ismixin(F.Counter)
    @test ROSNode.ismixin(F.Other)
    @test !ROSNode.ismixin(Int)

    @test ROSNode.node_kind("Counter") === F.Counter    # registered by ros_init! at load
    @test ROSNode.node_kind("Other")   === F.Other
    @test ROSNode.node_kind("Rig")     === F.Rig

    @test fieldnames(ROSNode._ensure_schema!(F.Counter)) == (:fps, :label)

    @testset "@precompile_nodes bake survives to runtime" begin
        # The bake markers are module-local `const`s generated by `@precompile_nodes` at the
        # package's precompile. Their presence after a load that does NOT re-run the module
        # body proves the typed-accessor codegen rode the pkgimage (a ROSNode-global would be
        # empty here — the `_MIXINS` trap). The named struct/const IS the reuse marker that
        # stops the runtime materialise path re-`Core.eval`ing (which would invalidate the
        # baked handler specialisations).
        psym = ROSNode._pschema_sym(F.Counter)                # __ros_pschema_Counter__
        esym = ROSNode._entities_sym(F.Counter)               # __ros_entities_Counter__
        @test isdefined(F, psym)                              # typed parameter schema P_M
        @test isdefined(F, esym)                              # entities(m)::PortsNT capture
        @test getfield(F, psym) === ROSNode.pschema(F.Counter)
        # The baked PortsNT matches what `_ports_nt_type` derives from the specs (the same
        # type the runtime materialise path would capture) — guards `_handle_type` exactness.
        @test getfield(F, esym) === ROSNode._ports_nt_type(ROSNode.mixin_spec(F.Counter).ports)
        # `entities(m::Counter)` is now a type-stable method returning that concrete NamedTuple,
        # not the generic `entities(::Component)` fallback.
        @test Base.return_types(ROSNode.entities, (F.Counter,))[1] === getfield(F, esym)

        # The reaction handlers were precompiled by the bake, so their MethodInstances are in the
        # method cache right after LOAD — no `run`, no warm, no race. A precompiled-or-executed MI
        # carries a CodeInstance in `.cache`; this proves the bake reached the user handler. The
        # reactions come from the spec, exactly what `_anchor_reactions!` precompiled.
        cached(f, ts) = any(mi -> mi isa Core.MethodInstance && mi.specTypes <: Base.signature_type(f, ts) &&
                                  isdefined(mi, :cache),
                            Iterators.flatten(Base.specializations(m) for m in methods(f, ts)))
        tickp   = only(p for p in sp.ports if p.kind === :timer)         # @every handler
        ingestp = only(p for p in sp.ports if p.kind === :subscription)  # @hears handler
        @test cached(tickp.reaction, (F.Counter,))
        @test cached(ingestp.reaction, (F.Counter, ingestp.msgtype))

        # The wire CODECS the bake anchors over the fixture's own message/service types — the
        # dominant first-message JIT, anchored by `_anchor_reactions!` — are in the cache right
        # after LOAD with no run, proving the codec bake rode the pkgimage (not just that the
        # signatures resolve, which `precompile()` forces even on a degenerate path — the MF1 trap).
        # NB: the endpoint-BUILDER MIs (`_make_publisher`/`_materialize_ports!`/`ParameterServer`)
        # that `_anchor_construction!` precompiles do NOT survive into a consuming package's image
        # (external ROSNode methods specialised on the package's types are inferred-only or pruned,
        # unlike the `@generated` codecs and the package-owned handlers) — so the construction tier
        # is verified by signature-resolution in component_entities_static.jl, not cache-presence.
        @test cached(ROSNode.decode_owned, (Memory{UInt8}, Type{ingestp.msgtype}))   # @hears decode
        srvp = only(p for p in sp.ports if p.kind === :service)                      # @serves codec
        @test cached(ROSNode.decode_owned, (Memory{UInt8}, Type{ROSNode.request_type(srvp.msgtype)}))
        @test cached(ROSNode.encode, (ROSNode.response_type(srvp.msgtype),))

        # The accessor-gated `Mover` action mixin: its goal/result/feedback codecs ride the image
        # too (over fixture-generated action types), proving the accessor-independent action bake.
        moverp   = only(p for p in ROSNode.mixin_spec(F.Mover).ports if p.kind === :action)
        msupport = ROSNode.ActionTypeSupport(typeof(moverp.reaction))
        @test cached(ROSNode.decode_owned, (Memory{UInt8}, Type{ROSNode.goal_type(msupport)}))
        @test cached(ROSNode.encode, (ROSNode.result_type(msupport),))
        @test cached(ROSNode.encode, (ROSNode.feedback_type(msupport),))
    end

    @testset "BYO __init__ keeps ROSNode initializing" begin
        spb = ROSNode.mixin_spec(B.Solo)
        @test [p.name for p in spb.params] == [:gain]
        @test Set((p.name, p.kind) for p in spb.ports) == Set([(:beat, :timer)])
        @test ROSNode.ismixin(B.Solo)
        @test ROSNode.node_kind("Solo") === B.Solo
        @test fieldnames(ROSNode._ensure_schema!(B.Solo)) == (:gain,)
        # Bake survives under a BYO __init__ module too.
        @test isdefined(B, ROSNode._pschema_sym(B.Solo))
        @test isdefined(B, ROSNode._entities_sym(B.Solo))
    end
end
"""

@testset "component precompilation survival" begin
    fixturedir = abspath(joinpath(@__DIR__, "..", "fixtures", "PrecompMixinFixture"))
    @test isfile(joinpath(fixturedir, "src", "PrecompMixinFixture.jl"))

    # The fixture's own UUID and its ROSNode dep UUID, read from its Project.toml by
    # regex (no TOML stdlib dep — it isn't on the test sandbox's path).
    fixtext  = read(joinpath(fixturedir, "Project.toml"), String)
    fix_uuid = match(r"(?m)^uuid *= *\"([^\"]+)\"", fixtext).captures[1]
    ros_uuid = match(r"(?m)^ROSNode *= *\"([^\"]+)\"", fixtext).captures[1]

    # The Manifest Julia actually resolves for the active project (the workspace root in
    # this repo; a sandbox manifest under `Pkg.test`). Its dir is the base for the
    # relative `path =` entries of workspace-member packages.
    manifest = Base.project_file_manifest_path(Base.active_project())
    @test manifest !== nothing && isfile(manifest)
    mroot = dirname(manifest)

    envdir = mktempdir()
    try
        # Reuse the resolved manifest, absolutizing relative member paths so they still
        # point at the real package sources from the temp env's location.
        man = read(manifest, String)
        man = replace(man, r"(?m)^path = \"(?!/)([^\"]+)\"$" =>
            s -> "path = \"" * joinpath(mroot, match(r"\"(.+)\"", s).captures[1]) * "\"")
        man *= """

        [[deps.PrecompMixinFixture]]
        deps = ["ROSNode"]
        path = "$fixturedir"
        uuid = "$fix_uuid"
        version = "0.0.1"
        """
        write(joinpath(envdir, "Manifest.toml"), man)
        write(joinpath(envdir, "Project.toml"),
              "[deps]\nPrecompMixinFixture = \"$fix_uuid\"\nROSNode = \"$ros_uuid\"\n")
        checkfile = joinpath(envdir, "precomp_check.jl")
        write(checkfile, _PRECOMP_CHECK)

        cmd = `$(Base.julia_cmd()) --project=$envdir --startup-file=no --color=no $checkfile`
        out = IOBuffer()
        # `Base.`-qualified: ROSNode exports `run` (node runner) and `success` (a
        # settlement outcome), which shadow the process builtins under `using ROSNode`.
        ok = Base.success(Base.run(pipeline(ignorestatus(cmd); stdout = out, stderr = out)))
        ok || @info "precompile-fixture subprocess output" log = String(take!(out))
        @test ok
    finally
        rm(envdir; recursive = true, force = true)
    end
end
