# §12.2 weak-static subscription — the on-the-wire type backstop (A2). A normal
# (exact) sub opens on its concrete type keyexpr, so the wire can't even deliver a
# wrong type; the graph detector covers discovery. A `match=:weak` sub instead
# wildcard-matches the topic (off-type samples DO arrive) and runs `check_sample_type`
# per sample: a wire type/version ≠ its declared `T` fires `on_type_mismatch` and is
# dropped before decode, while a matching sample is delivered normally. This pins
# that the dormant backstop is now wired and fires (it never had a caller before).

using ROSNode
using ROSNode: Context, Node, Publisher, Subscription, publish, on_type_mismatch,
               WireKeyValue
using Test

const _TMEP = isdefined(Main, :ROS_TEST_EP) ? Main.ROS_TEST_EP :
              get(ENV, "ROS_TEST_EP", "tcp/localhost:7447")

# A second, distinct ROS type on the same topic — different name ⇒ a `:name`
# mismatch the backstop must catch. Generated by name from the BYO fixtures (the
# relative root resolves against this file: test/discovery → test/fixtures/byo).
module _TMTypes
    using ROSNode
    @ros_import from="../fixtures/byo" "robot_msgs/msg/Widget"
end
const Widget = _TMTypes.robot_msgs.msg.Widget

@testset "weak-static subscription: on-the-wire type backstop (§12.2/A2)" begin
    Context(; peers = [_TMEP], localhost_only = true) do ctx
        node = Node(ctx, "wk")
        got  = Channel{Any}(16)        # decoded messages the handler actually saw
        mism = Channel{Any}(16)        # TypeMismatch events fired by the backstop

        on_type_mismatch(ctx) do tm
            put!(mism, tm)
        end
        # Declares WireKeyValue but wildcard-matches /wk, so the Widget below arrives.
        sub = Subscription(node, "/wk", WireKeyValue; match = :weak) do m
            put!(got, m)
        end
        pubWidget = Publisher(node, "/wk", Widget)
        pubKV     = Publisher(node, "/wk", WireKeyValue)
        sleep(0.5)                     # let the routes match

        publish(pubWidget, Widget(label = "x", count = Int32(1), samples = Float64[]))
        publish(pubKV, WireKeyValue(key = "k", value = "v"))

        # Wait for both signals: the matching KV delivered AND the mismatch fired.
        timedwait(5.0; pollint = 0.02) do
            isready(got) && isready(mism)
        end

        # The off-type Widget was caught by the backstop: a :name mismatch fired.
        @test isready(mism)
        tm = take!(mism)
        @test tm.reason === :name
        @test occursin("Widget", tm.suggestion)

        # The matching WireKeyValue was decoded and delivered.
        @test isready(got)
        kv = take!(got)
        @test String(kv.key) == "k"
        @test String(kv.value) == "v"

        # The Widget was dropped *before* decode — it never reached the handler.
        sleep(0.2)                     # allow any erroneous extra delivery to surface
        @test !isready(got)
    end
end
